#!/usr/bin/env python
"""Emit the frontend's copy of the sandbox layout.

The browser classifies agent paths (memory, memo, skills, user profile) and
has to agree with the backend on every prefix. Rather than a second hand-kept
list, this writes ``agentPaths.generated.ts`` from ``SandboxLayout``, and a
unit test regenerates and diffs it so drift fails CI.

    uv run python scripts/gen_agent_paths.py            # write the file
    uv run python scripts/gen_agent_paths.py --check    # fail if stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
# Both roots: ``ptc_agent`` is imported bare (one module identity), and the
# package it pulls in reaches ``src.*`` from the repo root.
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "src"))

from ptc_agent.core.paths import (  # noqa: E402
    AGENT_SYSTEM_DIRS,
    LEGACY_ROOT_CODE_DIR,
    LEGACY_ROOT_DIRS,
    LEGACY_ROOT_TOOLS_DIR,
    MEMO_INDEX_FILENAME,
    MEMORY_INDEX_FILENAME,
    SANDBOX_ROOTS,
    USER_PROFILE_PORTFOLIO_FILE,
    USER_PROFILE_PREFERENCE_FILE,
    USER_PROFILE_WATCHLIST_FILE,
    SandboxLayout,
    WorkspaceLayout,
)

OUTPUT = REPO_ROOT / "web/src/pages/ChatAgent/utils/agentPaths.generated.ts"

_HEADER = """\
// Generated by scripts/gen_agent_paths.py from src/ptc_agent/core/paths.py.
// Do not edit: run `uv run python scripts/gen_agent_paths.py` instead. The
// unit test tests/unit/core/test_sandbox_layout.py regenerates and diffs this
// file, so an edit here fails CI rather than silently diverging.
"""


def _string_list(name: str, values: tuple[str, ...] | list[str]) -> str:
    body = "".join(f"  '{v}',\n" for v in values)
    return f"export const {name} = [\n{body}] as const;\n"


def _js_string(text: str) -> str:
    """A single-quoted literal, escaping everything outside printable ASCII."""
    return "'" + "".join(
        c if " " <= c <= "~" and c not in "'\\" else f"\\u{{{ord(c):x}}}"
        for c in text
    ) + "'"


def _casefold_exceptions() -> list[tuple[str, str]]:
    """Every code point Python's ``casefold`` maps differently from ``lower``.

    The server keys workspace folders with ``casefold`` and the browser has only
    ``toLowerCase``, which agrees with ``lower`` on every code point both
    runtimes' Unicode versions assign. The set is the same under Unicode 15.0
    through 16.0.
    """
    return [
        (c, c.casefold())
        for c in map(chr, range(sys.maxunicode + 1))
        if c.casefold() != c.lower()
    ]


def render() -> str:
    layout = SandboxLayout.default()
    out = [_HEADER, "\n"]

    out.append("/** Working directory of the stock sandbox image. */\n")
    out.append(f"export const SANDBOX_ROOT = '{layout.root}';\n\n")

    out.append(
        "/** Every root a sandbox path may be spelled with, current one first.\n"
        " *  Rootless form (no leading slash), callers strip that first. */\n"
    )
    out.append(
        _string_list(
            "SANDBOX_ROOT_PREFIXES",
            tuple(f"{root.lstrip('/')}/" for root in SANDBOX_ROOTS),
        )
    )
    out.append("\n")

    # The browser matches a path's leading segments, so each name is emitted
    # from the class that owns it. The exported name is given separately
    # because the browser keeps its own vocabulary: MEMORY_WORKSPACE_DIR names
    # the workspace memory tier there, whose relative path is MEMORY_DIR here.
    out.append("// Root-relative directories the path classifier keys off.\n")
    for export_name, owner, attr in (
        ("MEMORY_USER_DIR", SandboxLayout, "MEMORY_USER_DIR"),
        ("MEMORY_WORKSPACE_DIR", WorkspaceLayout, "MEMORY_DIR"),
        ("MEMO_USER_DIR", SandboxLayout, "MEMO_USER_DIR"),
        ("USER_PROFILE_DIR", SandboxLayout, "USER_PROFILE_DIR"),
        ("SKILLS_DIR", WorkspaceLayout, "SKILLS_DIR"),
        ("THREADS_DIR", WorkspaceLayout, "THREADS_DIR"),
        ("LARGE_TOOL_RESULTS_DIR", WorkspaceLayout, "LARGE_TOOL_RESULTS_DIR"),
        ("AGENTS_DIR", SandboxLayout, "AGENTS_DIR"),
        ("INTERNAL_DIR", SandboxLayout, "INTERNAL_DIR"),
    ):
        out.append(f"export const {export_name} = '{getattr(owner, attr)}';\n")
    out.append("\n")

    out.append(
        "/** The agent's own notes file at the workspace root: runtime context\n"
        " *  the model reads every turn, never a deliverable. */\n"
    )
    out.append(f"export const AGENT_MD_FILE = '{WorkspaceLayout.AGENT_MD_FILE}';\n\n")

    out.append("export const MEMORY_INDEX_FILENAME = ")
    out.append(f"'{MEMORY_INDEX_FILENAME}';\n")
    out.append(f"export const MEMO_INDEX_FILENAME = '{MEMO_INDEX_FILENAME}';\n\n")

    out.append("/** The three virtual JSON files that UserDataBackend serves. */\n")
    out.append("export const USER_PROFILE_FILES = {\n")
    out.append(f"  portfolio: '{USER_PROFILE_PORTFOLIO_FILE}',\n")
    out.append(f"  watchlist: '{USER_PROFILE_WATCHLIST_FILE}',\n")
    out.append(f"  preference: '{USER_PROFILE_PREFERENCE_FILE}',\n")
    out.append("} as const;\n\n")

    out.append(
        "/** Agent-infrastructure dirs at the sandbox root, collapsed by\n"
        " *  default in the file panel. Source: AGENT_SYSTEM_DIRS. */\n"
    )
    out.append(_string_list("AGENT_SYSTEM_DIRS", tuple(sorted(AGENT_SYSTEM_DIRS))))
    out.append("\n")

    out.append(
        "/** Root dirs an earlier layout owned, still present in a sandbox\n"
        " *  reused across its migration: `tools` moved under `_internal` in\n"
        " *  v4, `code` under `.system` in v2. A name-based filter needs them\n"
        " *  alongside AGENT_SYSTEM_DIRS. */\n"
    )
    out.append(f"export const LEGACY_ROOT_TOOLS_DIR = '{LEGACY_ROOT_TOOLS_DIR}';\n")
    out.append(f"export const LEGACY_ROOT_CODE_DIR = '{LEGACY_ROOT_CODE_DIR}';\n")
    out.append(_string_list("LEGACY_ROOT_DIRS", LEGACY_ROOT_DIRS))
    out.append("\n")

    out.append(
        "/** Code points whose `casefold` differs from `toLowerCase`. The server\n"
        " *  matches former workspace folders by `casefold`, so the browser folds\n"
        " *  these from the table and every other code point with `toLowerCase`. */\n"
    )
    out.append("export const CASEFOLD_EXCEPTIONS: Readonly<Record<string, string>> = {\n")
    pairs = [f"{_js_string(k)}: {_js_string(v)}," for k, v in _casefold_exceptions()]
    for i in range(0, len(pairs), 4):
        out.append("  " + " ".join(pairs[i : i + 4]) + "\n")
    out.append("};\n")

    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed file differs from the emission",
    )
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(f"{OUTPUT} is stale, rerun scripts/gen_agent_paths.py")
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
